apiVersion: v1
kind: ConfigMap
metadata:
  name: irrigation-config
  namespace: default
data:
  # Configuration commune
  EUREKA_SERVER_URL: "http://eureka-server:8761/eureka/"
  CONFIG_SERVER_URL: "http://config-server:8888"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
